USE MASTER

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'DB')
BEGIN
	ALTER DATABASE DB
	SET SINGLE_USER
	WITH ROLLBACK IMMEDIATE

	DROP DATABASE DB
END

CREATE DATABASE DB
GO

USE DB

CREATE TABLE PRODUTO_CI_AS
(
	COD_PRODUTO INT IDENTITY, 
	NOME_PRODUTO VARCHAR(50) UNIQUE, 
	PRECO_PRODUTO DEC(9, 2)
)

CREATE TABLE PRODUTO_CI_AI
(
	COD_PRODUTO INT IDENTITY, 
	NOME_PRODUTO VARCHAR(50) COLLATE LATIN1_GENERAL_CI_AI UNIQUE, 
	PRECO_PRODUTO DEC(9, 2)
)

CREATE TABLE PRODUTO_CS_AS
(
	COD_PRODUTO INT IDENTITY, 
	NOME_PRODUTO VARCHAR(50) COLLATE LATIN1_GENERAL_CS_AS UNIQUE, 
	PRECO_PRODUTO DEC(9, 2)
)

INSERT PRODUTO_CS_AS
VALUES ('ACUCAR', 1), 
	('açúcar', 1) 

INSERT PRODUTO_CI_AI
VALUES ('ACUCAR', 1), 
	('açúcar', 1) --acucar -> ACUCAR -> AÇÚCAR

INSERT PRODUTO_CI_AS
VALUES ('ACUCAR', 1), 
	('açúcar', 1) --AÇÚCAR

SELECT *
FROM PRODUTO_CS_AS

SELECT *
FROM PRODUTO_CI_AI

SELECT *
FROM PRODUTO_CI_AS

--SELECT *
--FROM PRODUTO_CS_AS
--UNION
--SELECT *
--FROM PRODUTO_CI_AS

SELECT COD_PRODUTO, 
	NOME_PRODUTO COLLATE LATIN1_GENERAL_CI_AS, 
	PRECO_PRODUTO
FROM PRODUTO_CS_AS
UNION ALL
SELECT COD_PRODUTO, 
	NOME_PRODUTO, 
	PRECO_PRODUTO
FROM PRODUTO_CI_AS

--------------------------------------
--ALTERAR TAMANHO DE ARQUIVO DO TEMPDB
--------------------------------------

ALTER DATABASE tempdb 
MODIFY FILE 
( 
	NAME = N'tempdev', 
	SIZE = 100MB 
)

ALTER DATABASE tempdb 
MODIFY FILE 
( 
	NAME = N'templog', 
	SIZE = 10MB 
)

--CRIAR DATABASE

USE MASTER 

DROP DATABASE DB

CREATE DATABASE DB

EXEC SP_HELPDB

EXEC SP_HELPDB DB

USE DB

EXEC SP_HELPFILEGROUP

EXEC SP_HELPFILE

USE MASTER 

DROP DATABASE DB

--UMA TABELA GRAAAAANDE

CREATE DATABASE DB
ON --PRIMARY
(
	NAME = 'DBD1', 
	FILENAME = 'C:\_E\DB.MDF', -- SERIA O DRIVE E (TALVEZ UM RAID 5)
	SIZE = 100MB, 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 10%
)
, 
(
	NAME = 'DBD2', 
	FILENAME = 'C:\_F\DB.NDF', -- SERIA O DRIVE F (TALVEZ UM RAID 5)
	SIZE = 100MB, 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 10%
)
LOG ON
(
	NAME = 'DBL', 
	FILENAME = 'C:\_G\DB.LDF', -- SERIA O DRIVE G (TALVEZ UM RAID 0)
	SIZE = 40MB, 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 10%
)

EXEC SP_HELPDB

EXEC SP_HELPDB DB

USE DB

CREATE TABLE PESSOA 
(
	COD_PESSOA INT IDENTITY,
	NOME_PESSOA CHAR(5000) 
)

--MOSTRAR CRESCIMENTO DOS ARQUIVOS DE DADOS E LOG

BEGIN TRAN

WHILE 1=1
	INSERT PESSOA
	VALUES (NEWID())

ROLLBACK TRAN

------------------------------
--MODELO DO WILTON DE QUEIROZ
------------------------------

CREATE TABLE [dbo].[tab1](
[cod] [int] NOT NULL,
[descricao] [varchar](50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
CONSTRAINT [PK_tab1] PRIMARY KEY CLUSTERED 
([cod] ASC) ON [PRIMARY]) ON [PRIMARY]

go

ALTER TABLE [dbo].[tab1] 
WITH CHECK ADD CONSTRAINT [CK_tab1] 
CHECK (([cod]<=(1000)))
go
ALTER TABLE [dbo].[tab1] CHECK CONSTRAINT [CK_tab1]

go
CREATE TABLE [dbo].[tab2](
[cod] [int] NOT NULL,
[descricao] [varchar](50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
CONSTRAINT [PK_tab2] PRIMARY KEY CLUSTERED 
([cod] ASC) ON [PRIMARY]) ON [PRIMARY]


ALTER TABLE [dbo].[tab2] 
WITH CHECK ADD CONSTRAINT [CK_tab2] 
CHECK (([cod]>(1000)))
GO

ALTER TABLE [dbo].[tab2] CHECK CONSTRAINT [CK_tab2]

GO

CREATE VIEW [dbo].[TAB] as
SELECT cod,descricao FROM tab1
UNION ALL
SELECT cod,descricao FROM tab2

INSERT INTO TAB(cod,descricao)
VALUES(1,'antigo')

INSERT INTO TAB(cod,descricao)
VALUES(1001,'novo')

SELECT * FROM TAB

UPDATE TAB SET descricao='novox'
WHERE cod=1001

SELECT * FROM TAB WHERE cod=1
SELECT * FROM TAB WHERE cod=1001
SELECT * FROM TAB 

--