USE MASTER
DROP DATABASE DB

CREATE DATABASE DB
ON --DADOS
(
	NAME='DB_DADOS', 
	FILENAME='C:\_E\DB.MDF'
)
, 
FILEGROUP INDICES --INDICES
(
	NAME='DB_INDICES', 
	FILENAME='C:\_F\DB.NDF'
)
LOG ON
(
	NAME='DB_LOG', 
	FILENAME='C:\_G\DB.LDF'
)
GO

USE DB

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY, 
	NOME_PRODUTO VARCHAR(50), 
	PRECO_PRODUTO DEC(9, 2)
)
--ON [PRIMARY]

EXEC SP_HELP PRODUTO

CREATE /*NONCLUSTERED*/ INDEX IDX_PRODUTO_NOME_PRODUTO
ON PRODUTO (NOME_PRODUTO)
ON INDICES

EXEC SP_HELPINDEX PRODUTO

INSERT PRODUTO
VALUES ('MARTELO', 10.10)

UPDATE PRODUTO
SET NOME_PRODUTO = LOWER(NOME_PRODUTO)

DELETE PRODUTO

CREATE CLUSTERED INDEX IDX_PRODUTO_COD_PRODUTO
ON PRODUTO(COD_PRODUTO)
--ON [PRIMARY]
ON INDICES

EXEC SP_HELPINDEX PRODUTO

EXEC SP_HELP PRODUTO

USE MASTER
DROP DATABASE DB

CREATE DATABASE DB
ON --DADOS
(
	NAME='DB_DADOS_A', 
	FILENAME='C:\_E\DB.PDF' --PODE!!!
)
, 
FILEGROUP OUTRO --MAIS DADOS
(
	NAME='DB_DADOS_B', 
	FILENAME='C:\_F\DB.XML' --PODE!!!
)
LOG ON
(
	NAME='DB_LOG', 
	FILENAME='C:\_G\DB.XLSX' --PODE!!!
)
GO

USE DB

CREATE TABLE TIPO_PRODUTO
(
	COD_TIPO_PRODUTO INT IDENTITY PRIMARY KEY, 
	NOME_TIPO_PRODUTO VARCHAR(50)
)
--ON PRIMARY

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY PRIMARY KEY, 
	NOME_PRODUTO VARCHAR(50), 
	COD_TIPO_PRODUTO INT REFERENCES TIPO_PRODUTO
)
ON OUTRO

INSERT TIPO_PRODUTO
VALUES ('FERRAMENTA'), 
	('MATERIAL ESCOLAR')

INSERT PRODUTO
VALUES ('MARRETA', 1), 
	('MARTELO', 1), 
	('CADERNO', 2)

SELECT *
FROM TIPO_PRODUTO TP
JOIN  PRODUTO P
	ON TP.COD_TIPO_PRODUTO = P.COD_TIPO_PRODUTO

USE MASTER
DROP DATABASE DB

CREATE DATABASE DB
ON --DADOS QUE MUDAM FREQUENTEMENTE
(
	NAME='DB_DADOS_A', 
	FILENAME='C:\_E\DB.MDF' 
)
, 
FILEGROUP OUTRO --DADOS QUE MUDAM RARAMENTE
(
	NAME='DB_DADOS_B', 
	FILENAME='C:\_F\DB.NDF' 
)
LOG ON
(
	NAME='DB_LOG', 
	FILENAME='C:\_G\DB.LDF'
)
GO

USE DB

CREATE TABLE CEP
(
	COD_CEP INT IDENTITY PRIMARY KEY, 
	TIPO_CEP VARCHAR(10),
	NOME_CEP VARCHAR(100),
	CIDADE_CEP VARCHAR(50), 
	UF_CEP CHAR(2), 
	CEP_CEP CHAR(8)
)
ON OUTRO

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY PRIMARY KEY, 
	NOME_PRODUTO VARCHAR(50), 
	PRECO_PRODUTO DEC(9, 2)
)
--ON [PRIMARY]

INSERT CEP
VALUES ('R', 'DOMINGOS DE MORAIS', 'SÃO PAULO', 'SP', '04010100'), 
	(NULL, NULL, 'POUSO ALEGRE', 'MG', '37550000')

INSERT PRODUTO 
VALUES ('MARTELO', 10)

--BKP FULL -> DADOS (PRIMARY + OUTRO) -> T

--BKP FILEGROUP -> DADOS (PRIMARY) SEMANAL -> t
--BKP FILEGROUP -> DADOS (OUTRO) DIÁRIO -> t

--FG + F + RAID + STORAGE (IOPS)
--HD (SATA3, SAS, SCSI)
--SSD

ALTER DATABASE DB
MODIFY FILEGROUP OUTRO DEFAULT 

CREATE TABLE X
(
	Y INT
)

EXEC SP_HELP X

ALTER DATABASE DB
MODIFY FILEGROUP [PRIMARY] DEFAULT 

USE MASTER
DROP DATABASE DB

CREATE DATABASE DB
GO

USE DB

CREATE TABLE TABELA
(
	CAMPO UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY, 
	NOME CHAR(2500)
)

DECLARE @X INT = 1 

WHILE @X <= 50000
BEGIN 
	INSERT TABELA (NOME)
	VALUES ('AGNALDO')

	SET @X += 1
END

EXEC sp_spaceused

EXEC sp_spaceused TABELA

DBCC SHOWCONTIG()

DBCC SHOWCONTIG('TABELA')

/*
Table: 'TABELA' (245575913); index ID: 1, database ID: 18
TABLE level scan performed.
- Pages Scanned................................: 18863
- Extents Scanned..............................: 2370
- Extent Switches..............................: 18860
- Avg. Pages per Extent........................: 8.0
- Scan Density [Best Count:Actual Count].......: 12.50% [2358:18861]
- Logical Scan Fragmentation ..................: 99.24%
- Extent Scan Fragmentation ...................: 0.04%
- Avg. Bytes Free per Page.....................: 3052.8
- Avg. Page Density (full).....................: 62.28%
*/

DBCC DBREINDEX('TABELA')

DBCC SHOWCONTIG('TABELA')

/*
Table: 'TABELA' (245575913); index ID: 1, database ID: 18
TABLE level scan performed.
- Pages Scanned................................: 12559
- Extents Scanned..............................: 1570
- Extent Switches..............................: 1569
- Avg. Pages per Extent........................: 8.0
- Scan Density [Best Count:Actual Count].......: 100.00% [1570:1570]
- Logical Scan Fragmentation ..................: 0.00%
- Extent Scan Fragmentation ...................: 0.25%
- Avg. Bytes Free per Page.....................: 521.4
- Avg. Page Density (full).....................: 93.56%
*/

DBCC INDEXDEFRAG('DB', 'TABELA', 1)

GO

BEGIN TRAN

DECLARE @X INT = 1 

WHILE @X <= 50000
BEGIN 
	INSERT TABELA (NOME)
	VALUES ('AGNALDO')

	SET @X += 1
END

COMMIT

EXEC sp_spaceused

DBCC SHOWCONTIG('TABELA')

DBCC DBREINDEX('TABELA')

DBCC SHOWCONTIG('TABELA')

DBCC SHRINKDATABASE('DB', 0)

EXEC SP_HELPFILE

DBCC SHRINKFILE('DB', 20)
DBCC SHRINKFILE('DB_LOG', 0)

USE MASTER

EXEC sp_detach_db 'DB'

EXEC sp_attach_db 'DB', 'C:\_E\DB.MDF'

BACKUP LOG DB
TO DISK = 'NUL'

/*
ERRO NO SP_ATTACH_DB 'SERVIDORSQL',
'E:\BANCODEDADOS\SERVIDORSQL.MDF',
'e:\BANCODEDADOS\servidorsql_1.NDF',
'f:\BANCODEDADOS\TABPAF\bd_tab_paf.ndf'
*/

--CREATE DATABASE SERVIDORSQL 
--ON
--(
--		NAME = 'SERVIDORSQL_A',
--	    FILENAME = 'E:\BANCODEDADOS\SERVIDORSQL.MDF'
--)
--, 
--FILEGROUP X
--(
--		NAME = 'SERVIDORSQL_B',
--	    FILENAME = 'E:\BANCODEDADOS\SERVIDORSQL_1.NDF'
--)
--, 
--FILEGROUP Y
--(
--		NAME = 'SERVIDORSQL_C',
--	    FILENAME = 'E:\BANCODEDADOS\BD_TAB_PAF.NDF'
--)
--FOR ATTACH_FORCE_REBUILD_LOG
--GO 

USE DB

EXEC SP_HELPFILE

ALTER DATABASE DB
ADD FILE
(
	NAME='DB_A', 
	FILENAME = 'C:\_F\DB.NDF', 
	SIZE=259MB
)
TO FILEGROUP [PRIMARY]

EXEC SP_HELPFILE

ALTER DATABASE DB
ADD FILEGROUP INDICES

EXEC sp_helpfilegroup

ALTER DATABASE DB
ADD FILE
(
	NAME='DB_INDICES', 
	FILENAME = 'C:\_G\DB.NDF', 
	SIZE=259MB
)
TO FILEGROUP INDICES

ALTER DATABASE DB
REMOVE FILE DB_INDICES

ALTER DATABASE DB
REMOVE FILEGROUP INDICES

EXEC sp_helpfile 

CREATE TABLE X
(
	Y INT
)

--UNS 30000 RECORDS
WHILE 1=1
	INSERT X VALUES (1)

--ALTER DATABASE DB
--REMOVE FILE DB_A

DBCC SHRINKFILE('DB_A', EMPTYFILE)

ALTER DATABASE DB
REMOVE FILE DB_A

EXEC SP_HELPFILE

SELECT * 
FROM INFORMATION_SCHEMA.TABLES

EXEC SP_HELPTEXT SP_HELP

GO

SELECT SO.TYPE_DESC 'TYPE', 
	SO.NAME AS 'NAME', 
	DS.NAME AS 'FILEGROUP'
FROM SYS.OBJECTS SO
JOIN SYS.INDEXES I
	ON SO.OBJECT_ID = I.OBJECT_ID
JOIN  SYS.DATA_SPACES DS
	ON DS.DATA_SPACE_ID = I.DATA_SPACE_ID
WHERE SO.TYPE IN ('V', 'U')

ALTER DATABASE DB
SET OFFLINE

ALTER DATABASE DB
MODIFY FILE 
(
	NAME = 'DB', 
	FILENAME = 'C:\_G\DB.MDF'
)

ALTER DATABASE DB
SET ONLINE

USE DB

EXEC SP_HELPFILE 

--MOSTRAR COPY DATABASE WIZARD

USE DB

EXEC SP_HELPFILE

ALTER DATABASE DB
MODIFY FILE
(
	NAME = 'DBD1', 
	FILENAME = 'C:\_F\DB.MDF'	
)
