BACKUP DATABASE DB
TO DISK = 'C:\_E\BKP.BAK', 
	DISK = 'C:\_F\BKP.BAK', 
	DISK = 'C:\_G\BKP.BAK' 

BACKUP DATABASE DB
TO DISK = 'C:\_E\BKP.BAK', 
	DISK = 'C:\_F\BKP.BAK', 
	DISK = 'C:\_G\BKP.BAK' 

RESTORE FILELISTONLY 
FROM DISK = 'C:\_E\BKP.BAK', 
	DISK = 'C:\_F\BKP.BAK', 
	DISK = 'C:\_G\BKP.BAK' 
 
RESTORE HEADERONLY 
FROM DISK = 'C:\_E\BKP.BAK', 
	DISK = 'C:\_F\BKP.BAK', 
	DISK = 'C:\_G\BKP.BAK' 
 
BACKUP DATABASE DB
TO DISK = 'C:\_E\BKP.BAK', 
	DISK = 'C:\_F\BKP.BAK', 
	DISK = 'C:\_G\BKP.BAK' 
WITH COMPRESSION, FORMAT

BACKUP DATABASE DB
TO DISK = 'C:\_E\BKP.BAK'  
MIRROR TO DISK = 'C:\_G\BKP.BAK' 
WITH COMPRESSION, FORMAT

SELECT COUNT(*) 
FROM DB..PESSOA

BACKUP DATABASE DB
TO DISK = 'C:\_E\BKP.BAK'  
WITH FORMAT

RESTORE HEADERONLY 
FROM DISK = 'C:\_E\BKP.BAK'

BACKUP DATABASE DB
TO DISK = 'C:\_E\BKP.BAK'  
WITH DIFFERENTIAL, 
	STATS = 1

USE DB

INSERT PESSOA 
SELECT NOME_PESSOA, 
	OBS_PESSOA
FROM PESSOA

BACKUP DATABASE DB
TO DISK = 'C:\_E\BKP.BAK'  
WITH DIFFERENTIAL, 
	STATS = 1

RESTORE HEADERONLY 
FROM DISK = 'C:\_E\BKP.BAK'

BACKUP DATABASE DB
TO DISK = 'C:\_E\BKP.BAK'  
WITH DIFFERENTIAL, 
	STATS = 1

RESTORE HEADERONLY 
FROM DISK = 'C:\_E\BKP.BAK'

BACKUP LOG DB
TO DISK = 'C:\_E\BKP.BAK'
WITH STATS = 1

BACKUP LOG DB
TO DISK = 'C:\_E\BKP.BAK'
WITH STATS = 1

RESTORE HEADERONLY 
FROM DISK = 'C:\_E\BKP.BAK'

DBCC SHRINKDATABASE('DB')

RESTORE HEADERONLY 
FROM DISK = 'C:\_E\BKP.BAK'

SELECT @@TRANCOUNT

RESTORE VERIFYONLY
FROM DISK = 'C:\_E\BKP.BAK'

RESTORE LABELONLY
FROM DISK = 'C:\_E\BKP.BAK'

EXEC MSDB..SP_DELETE_BACKUPHISTORY '20130101' 

EXEC MSDB..SP_DELETE_DATABASE_BACKUPHISTORY 'DB' 

SELECT *
FROM MSDB..BACKUPSET

BACKUP DATABASE DB
TO DISK = 'C:\_F\BKP.BKP'
WITH COPY_ONLY

USE DB

INSERT PESSOA
VALUES ('AGNALDO', 'O HOMEM, A LENDA, O MITO')

USE MASTER

BACKUP LOG DB
TO DISK = 'C:\_E\BKP.BAK'
WITH STATS = 1, 
	NORECOVERY

RESTORE HEADERONLY
FROM DISK = 'C:\_E\BKP.BAK'

--CONTINUA NO PRÓXIMO ARQUIVO...