USE MASTER

--TAIL-LOG BACKUP JÁ FOI FEITO NO ARQUIVO ANTERIOR

RESTORE HEADERONLY 
FROM DISK = 'C:\_E\BKP.BAK'

--1F, 4D, 5L, 6L, 7L

RESTORE FILELISTONLY
FROM DISK = 'C:\_E\BKP.BAK'

RESTORE DATABASE DB
FROM DISK = 'C:\_E\BKP.BAK'
WITH NORECOVERY, 
	STATS = 10 

RESTORE DATABASE DB
FROM DISK = 'C:\_E\BKP.BAK'
WITH NORECOVERY, 
	FILE = 4, 
	STATS = 10

RESTORE LOG DB
FROM DISK = 'C:\_E\BKP.BAK'
WITH NORECOVERY,
	FILE = 5, 
	STATS = 10

RESTORE LOG DB
FROM DISK = 'C:\_E\BKP.BAK'
WITH NORECOVERY,
	FILE = 6, 
	STATS = 10

RESTORE LOG DB
FROM DISK = 'C:\_E\BKP.BAK'
WITH FILE = 7, 
	STATS = 10 --RECOVERY!!!

SELECT COUNT(*)
FROM DB..PESSOA

--MUDAR PARA SIMPLE RECOVERY MODEL
--MUDAR PARA FULL RECOVERY MODEL

BACKUP LOG DB
TO DISK = 'C:\_E\BKP.BAK'

--2000 -> 2005 OU 2008/2008R2 -> 2012

