IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'DB')
BEGIN
	USE MASTER

	ALTER DATABASE DB
	SET SINGLE_USER
	WITH ROLLBACK IMMEDIATE

	DROP DATABASE DB
END

CREATE DATABASE DB
GO

USE DB

CREATE TABLE TIPO_PRODUTO
(
	COD_TIPO_PRODUTO INT IDENTITY PRIMARY KEY, 
	NOME_TIPO_PRODUTO VARCHAR(50) UNIQUE 
)

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY PRIMARY KEY, 
	NOME_PRODUTO VARCHAR(50) UNIQUE, 
	PRECO_PRODUTO DEC(9, 2) CHECK (PRECO_PRODUTO >= 0),  
	COD_TIPO_PRODUTO INT REFERENCES TIPO_PRODUTO 
)

/*
	CONTEÚDO DO ARQUIVO TIPO_PRODUTO.TXT
1	FERRAMENTA
2	MATERIAL DE ESCRITÓRIO
*/

/*
	CONTEÚDO DO ARQUIVO PRODUTO.TXT
10	MARRETA	10.1	1
20	MARTELO	20.2	1
30	SERROTE	30.33	1
40	GRAMPEADOR	4	2
*/

--C:\Users\agnaldo\Desktop\10775>BCP DB.DBO.TIPO_PRODUTO IN TIPO_PRODUTO.TXT -S . -T -c -C ACP -E

SELECT *
FROM TIPO_PRODUTO

--C:\Users\agnaldo\Desktop\10775>BCP DB.DBO.PRODUTO IN PRODUTO.TXT -S . -T -c -C ACP -E

SELECT *
FROM PRODUTO

--1@MARTELO@10.1@1#2@MARRETA@20.2@1#
-- BCP ... -t @ -r #

--C:\Users\agnaldo\Desktop\10775>BCP DB.DBO.TIPO_PRODUTO OUT OUT_TIPO_PRODUTO.TXT -S . -T -c -C ACP -E -t @ -r #

--C:\Users\agnaldo\Desktop\10775>BCP "SELECT P.*, TP.NOME_TIPO_PRODUTO FROM DB.DBO.PRODUTO P JOIN DB.DBO.TIPO_PRODUTO TP ON TP.COD_TIPO_PRODUTO = P.COD_TIPO_PRODUTO" QUERYOUT QUERY_PRODUTO_TIPO_PRODUTO.TXT -c -S . -T

SELECT *
FROM PRODUTO

--RECRIAR O BANCO, VAZIO...

BULK INSERT TIPO_PRODUTO
FROM 'C:\Users\agnaldo\Desktop\10775\TIPO_PRODUTO.TXT'
WITH
(
	KEEPIDENTITY, 
	MAXERRORS = 0, 
	CODEPAGE = 'ACP'
)

SELECT *
FROM TIPO_PRODUTO

BULK INSERT PRODUTO
FROM 'C:\Users\agnaldo\Desktop\10775\PRODUTO.TXT'
WITH
(
	KEEPIDENTITY, 
	MAXERRORS = 0, 
	CODEPAGE = 'ACP', 
	BATCHSIZE = 2,  --COMMIT A CADA 2 LINHAS
	FIRSTROW = 3
)

SELECT *
FROM PRODUTO

EXEC SP_HELPINDEX TIPO_PRODUTO

EXEC SP_HELPINDEX PRODUTO

ALTER INDEX PK__TIPO_PRO__853C24F210EF467A ON TIPO_PRODUTO DISABLE
ALTER INDEX PK__PRODUTO__AAF2697D50DE6731 ON PRODUTO DISABLE

--FAZER CÓPIA...

ALTER INDEX PK__TIPO_PRO__853C24F210EF467A ON TIPO_PRODUTO REBUILD
ALTER INDEX PK__PRODUTO__AAF2697D50DE6731 ON PRODUTO REBUILD
ALTER INDEX UQ__TIPO_PRO__FEA0711C13CFE7BA ON TIPO_PRODUTO REBUILD
ALTER INDEX UQ__PRODUTO__B510E7C7BF4A7170 ON PRODUTO REBUILD
--OU
ALTER INDEX ALL ON TIPO_PRODUTO REBUILD
ALTER INDEX ALL ON PRODUTO REBUILD

EXEC SP_HELPCONSTRAINT TIPO_PRODUTO

EXEC SP_HELPCONSTRAINT PRODUTO

ALTER TABLE PRODUTO
NOCHECK CONSTRAINT CK__PRODUTO__PRECO_P__145C0A3F 

ALTER TABLE PRODUTO
NOCHECK CONSTRAINT FK__PRODUTO__COD_TIP__15502E78 
--OU
ALTER TABLE PRODUTO 
NOCHECK CONSTRAINT ALL

--FAZER A CÓPIA

ALTER TABLE PRODUTO
CHECK CONSTRAINT CK__PRODUTO__PRECO_P__145C0A3F 

ALTER TABLE PRODUTO
CHECK CONSTRAINT FK__PRODUTO__COD_TIP__15502E78 
--OU
ALTER TABLE PRODUTO 
CHECK CONSTRAINT ALL

--MOSTRAR IMPORT/EXPORT WIZARD

--MOSTRAR SSIS

GO

CREATE TRIGGER UTR_PRODUTO_INS
ON PRODUTO
FOR INSERT
AS
	SELECT * 
	FROM INSERTED
GO

INSERT PRODUTO
VALUES ('RÉGUA', 10, 2)

/*
	CONTEÚDO DE OUTROS_PRODUTOS.TXT
11	CADERNO	11	2
12	AGENDA	12	2
*/

BULK INSERT PRODUTO
FROM 'C:\Users\agnaldo\Desktop\10775\OUTROS_PRODUTOS.TXT'
WITH
(
	KEEPIDENTITY, 
	CODEPAGE = 'ACP', 
	FIRE_TRIGGERS
)

EXEC SP_ADDLINKEDSERVER 'JOKER\SQL2012'

SELECT * 
FROM SYS.SERVERS

SELECT *
FROM [JOKER\SQL2012].MASTER.SYS.OBJECTS

EXEC SP_DROPSERVER 'JOKER\SQL2012'

--SYNC TOY --> SINCRONISMO DE PASTAS

SELECT *
FROM OPENROWSET('SQLNCLI', --PROVIDER 
	'Data Source=JOKER\SQL2012;Initial Catalog=MASTER;Integrated Security=true;', --CONNECTION STRING
	'SELECT * FROM SYS.OBJECTS') AS DADOS --COMMAND	
	
EXEC SP_CONFIGURE 'SHOW ADVANCED OPTIONS', 1
GO
RECONFIGURE
GO
EXEC SP_CONFIGURE 'Ad Hoc Distributed Queries', 1
GO
RECONFIGURE
GO
EXEC SP_CONFIGURE 'SHOW ADVANCED OPTIONS', 0
GO
RECONFIGURE

SELECT *
FROM OPENROWSET('SQLNCLI', 
	'Server=JOKER\SQL2012;Database=MASTER;Uid=sa;pwd=abc123@;', 
	'SELECT * FROM SYS.OBJECTS') AS DADOS	

SELECT *
FROM OPENDATASOURCE
(
	'SQLNCLI',
    'Data Source=JOKER\SQL2012;Integrated Security=SSPI'
).MASTER.SYS.OBJECTS

SELECT *
FROM OPENQUERY([JOKER\SQL2012], 'SELECT * FROM SYS.OBJECTS')

SELECT *
FROM SYS.SERVERS
