EXEC SYS.SP_CONFIGURE 'SHOW ADVANCED OPTIONS', 1  
GO

RECONFIGURE WITH OVERRIDE
GO

EXEC SYS.SP_CONFIGURE 'C2 AUDIT MODE', 1
GO

EXEC SYS.SP_CONFIGURE 'COMMON CRITERIA COMPLIANCE ENABLED', 1
GO

RECONFIGURE WITH OVERRIDE
GO

EXEC SYS.SP_CONFIGURE 'SHOW ADVANCED OPTIONS', 0
GO

RECONFIGURE WITH OVERRIDE
GO

--BOOT NO SERVIÇO DO SQL SERVER

USE DB

DENY SELECT 
ON PRODUCAO.PRODUTO
TO ZE

GRANT SELECT
ON PRODUCAO.PRODUTO(COD_PRODUTO, NOME_PRODUTO)
TO ZE

EXECUTE AS USER = 'ZE'

SELECT * 
FROM PRODUCAO.PRODUTO

SELECT COD_PRODUTO, 
NOME_PRODUTO
FROM PRODUCAO.PRODUTO

REVERT

--INSERTED
--DELETED

CREATE TABLE PRODUCAO.PRODUTO_LOG
(
	COD_PRODUTO INT, 
	PRECO_PRODUTO DEC(9, 2), 
	ACAO CHAR(1),
	APP_NAME SYSNAME DEFAULT APP_NAME(), 
	SUSER_SNAME SYSNAME DEFAULT SUSER_SNAME(), 
	USER_NAME SYSNAME DEFAULT USER_NAME(), 
	HOST_NAME SYSNAME DEFAULT HOST_NAME(), 
	DATA DATETIME2 DEFAULT SYSDATETIME(), 
	ID_TRANSACAO UNIQUEIDENTIFIER
)

GO

CREATE TRIGGER PRODUCAO.UTR_PRODUCAO_PRODUTO_UPDATE
ON PRODUCAO.PRODUTO
FOR UPDATE
AS
	DECLARE @ID_TRANSACAO UNIQUEIDENTIFIER = NEWID()

	INSERT PRODUCAO.PRODUTO_LOG(COD_PRODUTO, PRECO_PRODUTO, ACAO, ID_TRANSACAO)
	SELECT I.COD_PRODUTO, 
		I.PRECO_PRODUTO, 
		'I', 
		@ID_TRANSACAO
	FROM INSERTED I
	JOIN DELETED D ON I.COD_PRODUTO = D.COD_PRODUTO
	WHERE I.PRECO_PRODUTO <> D.PRECO_PRODUTO

	INSERT PRODUCAO.PRODUTO_LOG(COD_PRODUTO, PRECO_PRODUTO, ACAO, ID_TRANSACAO)
	SELECT D.COD_PRODUTO, 
		D.PRECO_PRODUTO, 
		'D', 
		@ID_TRANSACAO
	FROM INSERTED I
	JOIN DELETED D ON I.COD_PRODUTO = D.COD_PRODUTO
	WHERE I.PRECO_PRODUTO <> D.PRECO_PRODUTO
GO

SELECT *
FROM PRODUCAO.PRODUTO

UPDATE PRODUCAO.PRODUTO
SET PRECO_PRODUTO = PRECO_PRODUTO * 1.2
WHERE COD_TIPO_PRODUTO = 1

SELECT *
FROM PRODUCAO.PRODUTO

SELECT *
FROM PRODUCAO.PRODUTO_LOG
ORDER BY ID_TRANSACAO, COD_PRODUTO, ACAO

CREATE TABLE PRODUCAO.LOG
(
	TABELA SYSNAME, 
	ACAO CHAR(1),
	OBS VARCHAR(MAX), 
	APP_NAME SYSNAME DEFAULT APP_NAME(), 
	SUSER_SNAME SYSNAME DEFAULT SUSER_SNAME(), 
	USER_NAME SYSNAME DEFAULT USER_NAME(), 
	HOST_NAME SYSNAME DEFAULT HOST_NAME(), 
	DATA DATETIME2 DEFAULT SYSDATETIME(), 
	ID_TRANSACAO UNIQUEIDENTIFIER
)

GO

--DDL -> BEGIN TRAN -> ID
--DML -> ID DA TRAN

USE MASTER

CREATE SERVER AUDIT AUDITORIA_APP_LOG
TO APPLICATION_LOG
WITH
(
	QUEUE_DELAY = 1000, 
	ON_FAILURE = CONTINUE
)

USE DB

CREATE DATABASE AUDIT SPECIFICATION DB_SELECT
FOR SERVER AUDIT AUDITORIA_APP_LOG
ADD (SELECT ON SCHEMA::PRODUCAO BY public)

SELECT *
FROM SYS.SERVER_AUDITS

SELECT *
FROM SYS.SERVER_AUDIT_SPECIFICATIONS

SELECT *
FROM SYS.DATABASE_AUDIT_SPECIFICATIONS

USE MASTER

ALTER SERVER AUDIT AUDITORIA_APP_LOG
WITH
(
	STATE = ON
)


USE DB

ALTER DATABASE AUDIT SPECIFICATION DB_SELECT
WITH 
(
	STATE = ON
)

SELECT *
FROM SYS.SERVER_AUDITS

SELECT *
FROM SYS.SERVER_AUDIT_SPECIFICATIONS

SELECT *
FROM SYS.DATABASE_AUDIT_SPECIFICATIONS

SELECT *
FROM PRODUCAO.TIPO_PRODUTO

SELECT *
FROM PRODUCAO.PRODUTO

ALTER DATABASE AUDIT SPECIFICATION DB_SELECT
WITH 
(
	STATE = OFF
)

DROP DATABASE AUDIT SPECIFICATION DB_SELECT

USE MASTER

ALTER SERVER AUDIT AUDITORIA_APP_LOG
WITH
(
	STATE = OFF
)

DROP SERVER AUDIT AUDITORIA_APP_LOG

CREATE SERVER AUDIT AUDITORIA_FILE
TO FILE 
(
	FILEPATH = 'C:\Users\agnaldo\Desktop\ARQUIVOS'
)

ALTER SERVER AUDIT AUDITORIA_FILE
WITH
(
	STATE = ON
)

USE DB

CREATE DATABASE AUDIT SPECIFICATION DB_SELECT
FOR SERVER AUDIT AUDITORIA_FILE
ADD (SELECT ON SCHEMA::PRODUCAO BY public)

ALTER DATABASE AUDIT SPECIFICATION DB_SELECT
WITH 
(
	STATE = ON
)

SELECT * 
FROM PRODUCAO.TIPO_PRODUTO

SELECT * 
FROM PRODUCAO.PRODUTO

--SELECT * 
--FROM PRODUCAO.BATATINHA

SELECT *
FROM SYS.FN_GET_AUDIT_FILE('C:\Users\agnaldo\Desktop\ARQUIVOS\*', NULL, NULL)

ALTER DATABASE AUDIT SPECIFICATION DB_SELECT
WITH 
(
	STATE = OFF
)

DROP DATABASE AUDIT SPECIFICATION DB_SELECT

USE MASTER

ALTER SERVER AUDIT AUDITORIA_FILE
WITH
(
	STATE = ON
)

USE DB

CREATE DATABASE AUDIT SPECIFICATION DB_UPDATE
FOR SERVER AUDIT AUDITORIA_FILE
ADD (UPDATE ON SCHEMA::PRODUCAO BY public)

ALTER DATABASE AUDIT SPECIFICATION DB_UPDATE
WITH 
(
	STATE = OFF
)

ALTER DATABASE AUDIT SPECIFICATION DB_UPDATE
FOR SERVER AUDIT AUDITORIA_FILE
ADD (INSERT ON SCHEMA::PRODUCAO BY public)

ALTER DATABASE AUDIT SPECIFICATION DB_UPDATE
WITH 
(
	STATE = ON
)

UPDATE PRODUCAO.PRODUTO 
SET PRECO_PRODUTO = PRECO_PRODUTO*0.9

SELECT *
FROM SYS.fn_get_audit_file('C:\Users\agnaldo\Desktop\ARQUIVOS\*', NULL, NULL)
