IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'DB')
BEGIN
	USE MASTER

	ALTER DATABASE DB
	SET SINGLE_USER
	WITH ROLLBACK IMMEDIATE

	DROP DATABASE DB
END

CREATE DATABASE DB
GO

USE DB

GO

CREATE SCHEMA PRODUCAO

GO

CREATE TABLE PRODUCAO.TIPO_PRODUTO
(
	COD_TIPO_PRODUTO INT IDENTITY PRIMARY KEY, 
	NOME_TIPO_PRODUTO VARCHAR(50) UNIQUE 
)

CREATE TABLE PRODUCAO.PRODUTO
(
	COD_PRODUTO INT IDENTITY PRIMARY KEY, 
	NOME_PRODUTO VARCHAR(50) UNIQUE, 
	PRECO_PRODUTO DEC(9, 2) CHECK (PRECO_PRODUTO >= 0),  
	COD_TIPO_PRODUTO INT REFERENCES PRODUCAO.TIPO_PRODUTO 
)

INSERT PRODUCAO.TIPO_PRODUTO
VALUES ('FERRAMENTA'), 
	('MATERIAL DE ESCRITÓRIO')

INSERT PRODUCAO.PRODUTO
VALUES ('SERROTE', 10, 1), 
	('MARTELO', 20, 1), 
	('MARRETA', 30, 1), 
	('AGENDA', 40, 2)

CREATE TABLE LOG
(
	DATA_LOG DATETIME DEFAULT GETDATE(), 
	QTD_PRODUTOS_LOG INT,
	CATEGORIA_LOG VARCHAR(50)
)

GO

CREATE PROC PRODUCAO.USP_PRODUTO_CONSOLIDA
AS
	SET NOCOUNT ON

	INSERT LOG (QTD_PRODUTOS_LOG, CATEGORIA_LOG)
	SELECT COUNT(*), NOME_TIPO_PRODUTO
	FROM PRODUCAO.TIPO_PRODUTO TP
	JOIN PRODUCAO.PRODUTO P
		ON TP.COD_TIPO_PRODUTO = P.COD_TIPO_PRODUTO
	GROUP BY NOME_TIPO_PRODUTO
GO

SELECT *
FROM LOG

--MOSTRAR O USR NO JOB HISTORY

--ALTERAR A PROC (PASSO 1) PARA EXECUTAR COMO GUEST

--EXECUTAR E VER O ERRO NO JOB HISTORY

GRANT CONNECT TO GUEST

REVOKE CONNECT TO GUEST

--DROPAR A PROC JOB E A PRODUCAO.USP_PRODUTO_CONSOLIDA

EXEC XP_CREATE_SUBDIR 'C:\Users\agnaldo\Desktop\ORIGEM'
EXEC XP_CREATE_SUBDIR 'C:\Users\agnaldo\Desktop\DESTINO'

--CRIAR UM ARQUIVO NA PASTA ORIGEM

--CRIAR E EXECUTAR UM JOB CMDEXEC 

--IMAGINANDO UM ERRO DE PERMISSÃO (O NOSSO SQL SERVER AGENT ESTÁ EXECUTANDO SOB JOKER\AGNALDO)

CREATE CREDENTIAL EU
WITH IDENTITY = 'JOKER\AGNALDO',
	SECRET = 'abc123@'

SELECT *
FROM SYS.CREDENTIALS

USE MSDB

EXEC SP_ADD_PROXY @PROXY_NAME = 'PROXY EU', @CREDENTIAL_NAME = 'EU', @ENABLED = 1

EXEC SP_GRANT_PROXY_TO_SUBSYSTEM @PROXY_NAME = 'PROXY EU', @SUBSYSTEM_ID = 3

--ALTERAR O PASSO DO JOB PARA USAR ESSE PROXY
