--HABILITAR O USO DE PROCS (P.E. SEND MAIL)

EXEC SP_CONFIGURE 'show advanced options', 1
GO

RECONFIGURE

EXEC SP_CONFIGURE 'Database Mail XPs', 1
GO

RECONFIGURE

EXEC SP_CONFIGURE 'show advanced options', 0
GO

RECONFIGURE

USE MSDB

EXEC DBO.SYSMAIL_DELETE_MAILITEMS_SP '20130802'

EXEC DBO.SYSMAIL_DELETE_LOG_SP '20130802'

--MOSTRAR CONFIGURAÇÃO DO DATABASE MAIL NO DATABASE ENGINE

--MOSTRAR CONFIGURAÇÃO DO SQL SERVER AGENT

EXEC SP_CYCLE_ERRORLOG 

--MOSTRAR A PASTA COM OS LOGS DO DATABASE ENGINE

--CRIAR OPERATOR

GO

DECLARE @NAME SYSNAME
DECLARE @EMAIL VARCHAR(MAX)

DECLARE X CURSOR FAST_FORWARD
FOR
	SELECT NAME, 'DIABONALDO@LIVE.COM' AS EMAIL 
	FROM SYS.SQL_LOGINS
	--JOIN COM A TABELA ONDE ESTÁ O E-MAIL
	WHERE IS_DISABLED = 0
	
OPEN X

FETCH NEXT FROM X INTO @NAME, @EMAIL

WHILE @@FETCH_STATUS = 0
BEGIN 
	EXEC msdb.dbo.sp_add_operator @name=@NAME, 
			@enabled=1, 
			@weekday_pager_start_time=90000, 
			@weekday_pager_end_time=180000, 
			@saturday_pager_start_time=90000, 
			@saturday_pager_end_time=180000, 
			@sunday_pager_start_time=90000, 
			@sunday_pager_end_time=180000, 
			@pager_days=0, 
			@email_address=@EMAIL, 
			@category_name=N'[Uncategorized]'

	FETCH NEXT FROM X INTO @NAME, @EMAIL
END

CLOSE X
DEALLOCATE X

GO

--CRIAR ALERT E NOTIFICAR OPERATOR

SELECT 1/0

EXEC SP_ALTERMESSAGE 8134, 'WITH_LOG', 'true'

SELECT 1/0

EXEC SP_ADDMESSAGE 50001, 16, 'ERRO NA BAGAÇA %s', NULL, 'true', 'replace'

SELECT * 
FROM SYS.MESSAGES

RAISERROR(50001, 16, 1, 'TABELA')

SET LANGUAGE 'BRAZILIAN'

SELECT 1/0

SELECT *
FROM SYS.SYSLANGUAGES

SET LANGUAGE 'ENGLISH'
