--MOSTRAR SQL SERVER PROFILER

--MOSTRAR EXTENDED EVENTS PROFILER

--COLETAR DADOS PARA TUNING

DECLARE @X INT = 1

WHILE @X <= 10000
BEGIN
	INSERT PRODUCAO.PRODUTO
	VALUES (NEWID(), 10, 1)

	SET @X += 1
END

SELECT *
FROM PRODUCAO.PRODUTO 
WHERE PRECO_PRODUTO > 20

--MOSTRAR DATABASE ENGINE TUNING ADVISOR
