--MOSTRAR A CRIAÇÃO DE UM CENTRAL MANAGEMENT SERVER

--MOSTRAR A CRIAÇÃO DE UM GRUPO DE SERVIDORES

--MOSTRAR COMO SE REGISTRA/DESREGISTRA UM SERVIDOR DE UM GRUPO

--MOSTRAR COMO SE EXECUTA UMA QUERY NO GRUPO (EXECUTAR OS COMANDOS ABAIXO)
SELECT @@VERSION

SELECT * 
FROM SYS.OBJECTS

EXEC SP_LOCK

--VOLTAR A ESSA JANELA

--MOSTRAR DATA-TIER APPLICATION

--MOSTRAR EXTRACT + DEPLOY

--MOSTRAR EXPORT + IMPORT
